import random
from datetime import date
import time

def user_guess(upper_bound):
  """ User guesses random number generated by the computer

  Args:
      upper_bound (number): upper bound for the game is variable

  Returns:
      turn (number): Amount of turns it took for the player to guess correctly
  """
  turn = 1
  random_number = random.randint(1, upper_bound)
  guess = 0

  while guess != random_number:
    guess = int(input(f'{turn}: Guess a number between 1 and {upper_bound}: '))
    if guess < random_number:
      print('Sorry, guess again. Too low')
      turn += 1
    elif guess > random_number:
      print('Sorry, guess again. Too high')
      turn += 1

  print(f'\nCongratulations! {random_number} was the right number.')
  write_score_to_file("p", turn)

def computer_guess(upper_bound):
  """ Computer guesses number of the user. The user provides feedback for the computer

  Args:
      upper_bound (number): upper bound for the game is variable
  
  Returns:
      turn (number): Amount of turns it took for the computer to guess correctly
  """
  print(f"Think of a number between 1 and {upper_bound}")
  time.sleep(2)
  low = 1
  high = upper_bound
  feedback = ''
  turn = 1

  while feedback != 'C':
    if low != high:
      guess = random.randint(low, high)
    else:
      guess = low
    feedback = input(f'{turn}: Is {guess} too high (H), too low (L) or correct (C): ').upper()
    if feedback == 'H':
      high = guess - 1
      turn += 1
    elif feedback == 'L':
      low = guess + 1
      turn += 1

  print(f'\nThe computer guessed your number {guess} after {turn} turns correctly.')
  write_score_to_file("c", turn)


def write_score_to_file(player, score):
  today = date.today()
  f = open("./scores/guessNumber.txt", 'a')
  f.write(f'\n{today} | {player}        | {score}        ')

if __name__ == '__main__':
  print('\n \n Welcome to "Guess the number" \n')
  variant = int(input("Want to guess yourself (1) or let the computer guess your number (2): "))
  print("")
  if variant == 1:
    upper_bound = int(input('Enter a number as upper bound for the game: '))
    print(f'The computer came up with a number between 1 and {upper_bound}. Guess it!\n')
    user_guess(upper_bound)
  elif variant == 2:
    upper_bound = int(input('Enter a number as upper bound for the game: '))
    print(f'Think of a number and give feedback to the computer!')
    computer_guess(upper_bound)
  else:
    print("Invalid Input, try again!")